// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for IntelligenAPI.
    /// </summary>
    public static partial class IntelligenAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<DOListboxItem> ApiGetUnitListGet(this IIntelligenAPI operations)
            {
                return Task.Factory.StartNew(s => ((IIntelligenAPI)s).ApiGetUnitListGetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<DOListboxItem>> ApiGetUnitListGetAsync(this IIntelligenAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiGetUnitListGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='unitIDs'>
            /// </param>
            public static IList<DOUnitState> ApiGetUnitStatesGet(this IIntelligenAPI operations, string unitIDs = default(string))
            {
                return Task.Factory.StartNew(s => ((IIntelligenAPI)s).ApiGetUnitStatesGetAsync(unitIDs), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='unitIDs'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<DOUnitState>> ApiGetUnitStatesGetAsync(this IIntelligenAPI operations, string unitIDs = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiGetUnitStatesGetWithHttpMessagesAsync(unitIDs, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='dispatch'>
            /// </param>
            public static int? ApiPostDispatchPost(this IIntelligenAPI operations, DODispatch dispatch = default(DODispatch))
            {
                return Task.Factory.StartNew(s => ((IIntelligenAPI)s).ApiPostDispatchPostAsync(dispatch), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='dispatch'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> ApiPostDispatchPostAsync(this IIntelligenAPI operations, DODispatch dispatch = default(DODispatch), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiPostDispatchPostWithHttpMessagesAsync(dispatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
