// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DOCustomField
    {
        /// <summary>
        /// Initializes a new instance of the DOCustomField class.
        /// </summary>
        public DOCustomField() { }

        /// <summary>
        /// Initializes a new instance of the DOCustomField class.
        /// </summary>
        public DOCustomField(int? dispatchID = default(int?), int? customFieldID = default(int?), string customField = default(string), string label = default(string), int? typeID = default(int?), string type = default(string), string value = default(string), string identifier = default(string), bool? required = default(bool?), string dropDownListValues = default(string))
        {
            DispatchID = dispatchID;
            CustomFieldID = customFieldID;
            CustomField = customField;
            Label = label;
            TypeID = typeID;
            Type = type;
            Value = value;
            Identifier = identifier;
            Required = required;
            DropDownListValues = dropDownListValues;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchID")]
        public int? DispatchID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomFieldID")]
        public int? CustomFieldID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomField")]
        public string CustomField { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeID")]
        public int? TypeID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Required")]
        public bool? Required { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DropDownListValues")]
        public string DropDownListValues { get; set; }

    }
}
