// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DOWaypoint
    {
        /// <summary>
        /// Initializes a new instance of the DOWaypoint class.
        /// </summary>
        public DOWaypoint() { }

        /// <summary>
        /// Initializes a new instance of the DOWaypoint class.
        /// </summary>
        public DOWaypoint(int? dispatchID = default(int?), int? waypointID = default(int?), int? areaID = default(int?), string waypoint = default(string), double? latitude = default(double?), double? longitude = default(double?), int? sequence = default(int?))
        {
            DispatchID = dispatchID;
            WaypointID = waypointID;
            AreaID = areaID;
            Waypoint = waypoint;
            Latitude = latitude;
            Longitude = longitude;
            Sequence = sequence;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchID")]
        public int? DispatchID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WaypointID")]
        public int? WaypointID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AreaID")]
        public int? AreaID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Waypoint")]
        public string Waypoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sequence")]
        public int? Sequence { get; set; }

    }
}
