//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MJEntities3 : DbContext
    {
        public MJEntities3()
            : base("name=MJEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCompany> tblCompany { get; set; }
        public virtual DbSet<tblEvent> tblEvent { get; set; }
        public virtual DbSet<tblEventCategory> tblEventCategory { get; set; }
        public virtual DbSet<tblGroup> tblGroup { get; set; }
        public virtual DbSet<tblPlant> tblPlant { get; set; }
        public virtual DbSet<tblPlantHistory> tblPlantHistory { get; set; }
        public virtual DbSet<tblPlantLocation> tblPlantLocation { get; set; }
        public virtual DbSet<tblPlantPhase> tblPlantPhase { get; set; }
    }
}
