//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlant()
        {
            this.tblPlantHistory = new HashSet<tblPlantHistory>();
        }
    
        public long ID { get; set; }
        public long GroupID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlantHistory> tblPlantHistory { get; set; }
    }
}
