//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlantHistory
    {
        public long ID { get; set; }
        public long PlantID { get; set; }
        public long EventID { get; set; }
        public string Data { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }

        public virtual tblEventCategory tblEventtblEventCategory { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblPlant tblPlant { get; set; }
    }
}
