//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSocialRankAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx", ConfigurationName="wsSocialRankAPI.SocialRankAPISoap")]
    public interface SocialRankAPISoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx/Dowork", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSocialRankAPI.DoworkResponse> DoworkAsync(wsSocialRankAPI.DoworkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoworkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dowork", Namespace="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx", Order=0)]
        public wsSocialRankAPI.DoworkRequestBody Body;
        
        public DoworkRequest()
        {
        }
        
        public DoworkRequest(wsSocialRankAPI.DoworkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx")]
    public partial class DoworkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xData;
        
        public DoworkRequestBody()
        {
        }
        
        public DoworkRequestBody(string xData)
        {
            this.xData = xData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoworkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoworkResponse", Namespace="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx", Order=0)]
        public wsSocialRankAPI.DoworkResponseBody Body;
        
        public DoworkResponse()
        {
        }
        
        public DoworkResponse(wsSocialRankAPI.DoworkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andrivr.hopto.org/SocialRankAPI/SocialRankAPI.asmx")]
    public partial class DoworkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoworkResult;
        
        public DoworkResponseBody()
        {
        }
        
        public DoworkResponseBody(string DoworkResult)
        {
            this.DoworkResult = DoworkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SocialRankAPISoapChannel : wsSocialRankAPI.SocialRankAPISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SocialRankAPISoapClient : System.ServiceModel.ClientBase<wsSocialRankAPI.SocialRankAPISoap>, wsSocialRankAPI.SocialRankAPISoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SocialRankAPISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), SocialRankAPISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SocialRankAPISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SocialRankAPISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SocialRankAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSocialRankAPI.DoworkResponse> wsSocialRankAPI.SocialRankAPISoap.DoworkAsync(wsSocialRankAPI.DoworkRequest request)
        {
            return base.Channel.DoworkAsync(request);
        }
        
        public string DoworkAsync(string xData)
        {
            wsSocialRankAPI.DoworkRequest inValue = new wsSocialRankAPI.DoworkRequest();
            inValue.Body = new wsSocialRankAPI.DoworkRequestBody();
            inValue.Body.xData = xData;
            return ((wsSocialRankAPI.SocialRankAPISoap)(this)).DoworkAsync(inValue).ToString();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SocialRankAPISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SocialRankAPISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SocialRankAPISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://andrivr.hopto.org:8080/SocialRankApi/Socialrankapi.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SocialRankAPISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://andrivr.hopto.org:8080/SocialRankApi/Socialrankapi.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SocialRankAPISoap,
            
            SocialRankAPISoap12,
        }
    }
}
