// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DODestination2
    {
        /// <summary>
        /// Initializes a new instance of the DODestination2 class.
        /// </summary>
        public DODestination2() { }

        /// <summary>
        /// Initializes a new instance of the DODestination2 class.
        /// </summary>
        public DODestination2(int? dispatchID = default(int?), string destination = default(string), double? longitude = default(double?), double? latitude = default(double?), int? tolerance = default(int?))
        {
            DispatchID = dispatchID;
            Destination = destination;
            Longitude = longitude;
            Latitude = latitude;
            Tolerance = tolerance;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchID")]
        public int? DispatchID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Destination")]
        public string Destination { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tolerance")]
        public int? Tolerance { get; set; }

    }
}
