// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DODispatchUnit
    {
        /// <summary>
        /// Initializes a new instance of the DODispatchUnit class.
        /// </summary>
        public DODispatchUnit() { }

        /// <summary>
        /// Initializes a new instance of the DODispatchUnit class.
        /// </summary>
        public DODispatchUnit(int? unitID = default(int?), DateTime? dispatchETAUTC = default(DateTime?), string alias = default(string))
        {
            UnitID = unitID;
            DispatchETAUTC = dispatchETAUTC;
            Alias = alias;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitID")]
        public int? UnitID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchETAUTC")]
        public DateTime? DispatchETAUTC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Alias")]
        public string Alias { get; set; }

    }
}
