// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DOUnitState
    {
        /// <summary>
        /// Initializes a new instance of the DOUnitState class.
        /// </summary>
        public DOUnitState() { }

        /// <summary>
        /// Initializes a new instance of the DOUnitState class.
        /// </summary>
        public DOUnitState(string gPSDateTime = default(string), string receivedDateTime = default(string), int? unitID = default(int?), string iMEI = default(string), string cellNr = default(string), string userName = default(string), string alias = default(string), string unitType = default(string), long? eventID = default(long?), DateTime? gPSDateTimeUTC = default(DateTime?), DateTime? receivedDateTimeUTC = default(DateTime?), double? longitude = default(double?), double? latitude = default(double?), string location = default(string), int? altitude = default(int?), int? speed = default(int?), int? odometer = default(int?), int? usageTimeAccumulator = default(int?), int? nextServiceDueOn = default(int?), int? equipmentServiceDueOn = default(int?), int? heading = default(int?), bool? ignitionStatus = default(bool?), bool? motionStatus = default(bool?), int? batteryLevelPercentage = default(int?), double? batteryVoltageUnit = default(double?), double? batteryVoltageVehicle = default(double?), string vehicleRegistrationNo = default(string), string temperature = default(string), string status = default(string), int? numberOfSatellitesInView = default(int?), int? markerID = default(int?), string markerColor = default(string), string labelBackColor = default(string), IList<int?> groupIDs = default(IList<int?>), bool? panic = default(bool?), DateTime? dispatchETAUTC = default(DateTime?), int? etaDispatchID = default(int?), IList<DOUnitDispatch> dispatches = default(IList<DOUnitDispatch>))
        {
            GPSDateTime = gPSDateTime;
            ReceivedDateTime = receivedDateTime;
            UnitID = unitID;
            IMEI = iMEI;
            CellNr = cellNr;
            UserName = userName;
            Alias = alias;
            UnitType = unitType;
            EventID = eventID;
            GPSDateTimeUTC = gPSDateTimeUTC;
            ReceivedDateTimeUTC = receivedDateTimeUTC;
            Longitude = longitude;
            Latitude = latitude;
            Location = location;
            Altitude = altitude;
            Speed = speed;
            Odometer = odometer;
            UsageTimeAccumulator = usageTimeAccumulator;
            NextServiceDueOn = nextServiceDueOn;
            EquipmentServiceDueOn = equipmentServiceDueOn;
            Heading = heading;
            IgnitionStatus = ignitionStatus;
            MotionStatus = motionStatus;
            BatteryLevelPercentage = batteryLevelPercentage;
            BatteryVoltageUnit = batteryVoltageUnit;
            BatteryVoltageVehicle = batteryVoltageVehicle;
            VehicleRegistrationNo = vehicleRegistrationNo;
            Temperature = temperature;
            Status = status;
            NumberOfSatellitesInView = numberOfSatellitesInView;
            MarkerID = markerID;
            MarkerColor = markerColor;
            LabelBackColor = labelBackColor;
            GroupIDs = groupIDs;
            Panic = panic;
            DispatchETAUTC = dispatchETAUTC;
            EtaDispatchID = etaDispatchID;
            Dispatches = dispatches;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPSDateTime")]
        public string GPSDateTime { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedDateTime")]
        public string ReceivedDateTime { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitID")]
        public int? UnitID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IMEI")]
        public string IMEI { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CellNr")]
        public string CellNr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Alias")]
        public string Alias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitType")]
        public string UnitType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EventID")]
        public long? EventID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPSDateTimeUTC")]
        public DateTime? GPSDateTimeUTC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedDateTimeUTC")]
        public DateTime? ReceivedDateTimeUTC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Altitude")]
        public int? Altitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Speed")]
        public int? Speed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Odometer")]
        public int? Odometer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageTimeAccumulator")]
        public int? UsageTimeAccumulator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NextServiceDueOn")]
        public int? NextServiceDueOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EquipmentServiceDueOn")]
        public int? EquipmentServiceDueOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Heading")]
        public int? Heading { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IgnitionStatus")]
        public bool? IgnitionStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotionStatus")]
        public bool? MotionStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BatteryLevelPercentage")]
        public int? BatteryLevelPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BatteryVoltageUnit")]
        public double? BatteryVoltageUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BatteryVoltageVehicle")]
        public double? BatteryVoltageVehicle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleRegistrationNo")]
        public string VehicleRegistrationNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Temperature")]
        public string Temperature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfSatellitesInView")]
        public int? NumberOfSatellitesInView { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarkerID")]
        public int? MarkerID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarkerColor")]
        public string MarkerColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LabelBackColor")]
        public string LabelBackColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GroupIDs")]
        public IList<int?> GroupIDs { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Panic")]
        public bool? Panic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchETAUTC")]
        public DateTime? DispatchETAUTC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EtaDispatchID")]
        public int? EtaDispatchID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Dispatches")]
        public IList<DOUnitDispatch> Dispatches { get; set; }

    }
}
