// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IntelligenAPICaller.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DOUnitDispatch
    {
        /// <summary>
        /// Initializes a new instance of the DOUnitDispatch class.
        /// </summary>
        public DOUnitDispatch() { }

        /// <summary>
        /// Initializes a new instance of the DOUnitDispatch class.
        /// </summary>
        public DOUnitDispatch(int? unitID = default(int?), int? dispatchID = default(int?), int? dispatchStatus = default(int?), IList<DODestination2> destinations = default(IList<DODestination2>), string orderNr = default(string), DateTime? startDateTimeUTC = default(DateTime?))
        {
            UnitID = unitID;
            DispatchID = dispatchID;
            DispatchStatus = dispatchStatus;
            Destinations = destinations;
            OrderNr = orderNr;
            StartDateTimeUTC = startDateTimeUTC;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitID")]
        public int? UnitID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchID")]
        public int? DispatchID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchStatus")]
        public int? DispatchStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Destinations")]
        public IList<DODestination2> Destinations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderNr")]
        public string OrderNr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDateTimeUTC")]
        public DateTime? StartDateTimeUTC { get; set; }

    }
}
