//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.wsGrowmeAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://andrivrddns.dlinkddns.com:8081//GrowmeAPI", ConfigurationName="wsGrowmeAPI.GrowmeWSSoap")]
    public interface GrowmeWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://andrivrddns.dlinkddns.com:8081//GrowmeAPI/DoWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DoWork(string xData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://andrivrddns.dlinkddns.com:8081//GrowmeAPI/DoWork", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string xData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GrowmeWSSoapChannel : Shared.wsGrowmeAPI.GrowmeWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrowmeWSSoapClient : System.ServiceModel.ClientBase<Shared.wsGrowmeAPI.GrowmeWSSoap>, Shared.wsGrowmeAPI.GrowmeWSSoap {
        
        public GrowmeWSSoapClient() {
        }
        
        public GrowmeWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrowmeWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrowmeWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrowmeWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string xData) {
            return base.Channel.DoWork(xData);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string xData) {
            return base.Channel.DoWorkAsync(xData);
        }
    }
}
