//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSocialRankAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://andrivr.hopto.org:8000/SocialRankAPI", ConfigurationName="wsSocialRankAPI.wsSocialRankAPISoap")]
    public interface wsSocialRankAPISoap
    {
        
        // CODEGEN: Generating message contract since element name xData from namespace http://andrivr.hopto.org:8000/SocialRankAPI is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://andrivr.hopto.org:8000/SocialRankAPI/DoWork", ReplyAction="*")]
        wsSocialRankAPI.DoWorkResponse DoWork(wsSocialRankAPI.DoWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://andrivr.hopto.org:8000/SocialRankAPI/DoWork", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSocialRankAPI.DoWorkResponse> DoWorkAsync(wsSocialRankAPI.DoWorkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoWorkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoWork", Namespace="http://andrivr.hopto.org:8000/SocialRankAPI", Order=0)]
        public wsSocialRankAPI.DoWorkRequestBody Body;
        
        public DoWorkRequest()
        {
        }
        
        public DoWorkRequest(wsSocialRankAPI.DoWorkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andrivr.hopto.org:8000/SocialRankAPI")]
    public partial class DoWorkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xData;
        
        public DoWorkRequestBody()
        {
        }
        
        public DoWorkRequestBody(string xData)
        {
            this.xData = xData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoWorkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoWorkResponse", Namespace="http://andrivr.hopto.org:8000/SocialRankAPI", Order=0)]
        public wsSocialRankAPI.DoWorkResponseBody Body;
        
        public DoWorkResponse()
        {
        }
        
        public DoWorkResponse(wsSocialRankAPI.DoWorkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://andrivr.hopto.org:8000/SocialRankAPI")]
    public partial class DoWorkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoWorkResult;
        
        public DoWorkResponseBody()
        {
        }
        
        public DoWorkResponseBody(string DoWorkResult)
        {
            this.DoWorkResult = DoWorkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsSocialRankAPISoapChannel : wsSocialRankAPI.wsSocialRankAPISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsSocialRankAPISoapClient : System.ServiceModel.ClientBase<wsSocialRankAPI.wsSocialRankAPISoap>, wsSocialRankAPI.wsSocialRankAPISoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsSocialRankAPISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsSocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), wsSocialRankAPISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSocialRankAPISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsSocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSocialRankAPISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsSocialRankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSocialRankAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSocialRankAPI.DoWorkResponse wsSocialRankAPI.wsSocialRankAPISoap.DoWork(wsSocialRankAPI.DoWorkRequest request)
        {
            return base.Channel.DoWork(request);
        }
        
        public string DoWork(string xData)
        {
            wsSocialRankAPI.DoWorkRequest inValue = new wsSocialRankAPI.DoWorkRequest();
            inValue.Body = new wsSocialRankAPI.DoWorkRequestBody();
            inValue.Body.xData = xData;
            wsSocialRankAPI.DoWorkResponse retVal = ((wsSocialRankAPI.wsSocialRankAPISoap)(this)).DoWork(inValue);
            return retVal.Body.DoWorkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSocialRankAPI.DoWorkResponse> wsSocialRankAPI.wsSocialRankAPISoap.DoWorkAsync(wsSocialRankAPI.DoWorkRequest request)
        {
            return base.Channel.DoWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSocialRankAPI.DoWorkResponse> DoWorkAsync(string xData)
        {
            wsSocialRankAPI.DoWorkRequest inValue = new wsSocialRankAPI.DoWorkRequest();
            inValue.Body = new wsSocialRankAPI.DoWorkRequestBody();
            inValue.Body.xData = xData;
            return ((wsSocialRankAPI.wsSocialRankAPISoap)(this)).DoWorkAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSocialRankAPISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSocialRankAPISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSocialRankAPISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/SocialRankAPI/wsSocialRankAPI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSocialRankAPISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/SocialRankAPI/wsSocialRankAPI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsSocialRankAPISoap,
            
            wsSocialRankAPISoap12,
        }
    }
}
