//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDAL")]
public interface IDAL
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDAL/DoWork", ReplyAction="http://tempuri.org/IDAL/DoWorkResponse")]
    object DoWork(object objData);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDALChannel : IDAL, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DALClient : System.ServiceModel.ClientBase<IDAL>, IDAL
{
    
    public DALClient()
    {
    }
    
    public DALClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DALClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DALClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DALClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public object DoWork(object objData)
    {
        return base.Channel.DoWork(objData);
    }
}
